services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80"

    environment:
      TZ: America/New_York
      WEBPASSWORD: ChangeThisNow

    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
